### ISSUE TITLE
No Host ID among Falcon filters list

### ISSUE THREAD

**Issue by SkyWheel** [CrowdStrike/Falcon-Toolkit#16]
Hi,
I can pass hostname by filter `Hostname=`, but I haven't found way how to pass Host IDs.

**Comment by ChristopherHammond13** [comment]
Hey! There are a couple of extra command line options available if you want to connect by ID.

- `-d` allows you to specify device IDs (AIDs) as a comma delimited list at the CLI.
- `-df` allows you to provide a list of AIDs in a file, new line delimited. This option exists to get round command line length limits that exist.

Let me know if those options work for you, and if you have any other questions. If this solution solves your issue, please feel free to close this issue out.

Thank you!

**Comment by SkyWheel** [comment]
Hi @ChristopherHammond13 ,
Thanks! That is exactly what I need. Besides, you already answered to my 2nd question about passing to the Falcon shell a file with a list of hosts🙂
Could you please also update the readme file with this and other options available but not listed. That would be really helpful.

**Comment by SkyWheel** [comment]
sorry, hiw exactly should I use `-df` option?
My command looks like:
`falcon shell -df <path_to_host_IDs_file> -s <path_to_script.rtr>`
Looks like it's not correct syntax...

**Comment by ChristopherHammond13** [comment]
Hey @SkyWheel, that syntax certainly looks like what _should_ be accepted, having reviewed the code again. Can you paste the specific error you receive, so I can double check whether this is a CLI syntax issue or an issue further downstream (i.e., during the connection process)? Thank you!

**Comment by ChristopherHammond13** [comment]
I have tested this as working. This is my current setup:
- Profile named `ServicesTest`
- File named `device_ids.txt` containing just one line: a Device ID / AID
- File named `test.rtr` containing just one line: the `ls` command

Invoked with:
```shell
$ falcon -p ServicesTest shell -df device_ids.txt -s test.rtr
```

The shell connects to the system with the ID in the file then immediately runs the `ls` command before dropping to a general prompt.

**Comment by ChristopherHammond13** [comment]
Closing this issue as I have not seen a reply within two weeks. Please feel free to re-open the issue if you have any further issues. Thank you!

**Comment by SkyWheel** [comment]
Sorry, can confirm everything works as expected.
Thank you!
