### ISSUE TITLE
Mixed case filter options

### ISSUE THREAD

**Issue by 59e5aaf4** [CrowdStrike/Falcon-Toolkit#40]
When trying to filter based on hostname, could it be possible to ignore the case ? It's just to avoid the following frustrating moment :D

```
$ falcon -p ddev host_search -f OS=Windows -f hostname=VM-azdaz2022
Exception: hostname
$ falcon -p ddev host_search -f OS=Windows -f Hostname=VM-azdaz2022
VM-azdaz2022 - (id)
```

Thanks !

**Comment by ChristopherHammond13** [comment]
Hey! Thank you for raising your feature recommendations / issues! I'm going through them now and getting them categorised

This one in particular _may_ be tricky from our side as we build an FQL query on the backend and pipe this through to Falcon verbatim, so I need to see whether we can coerce FQL case insensitivity through the API (I believe not, but will ask).
