### ISSUE TITLE
Documentation - how does the RTR command quoting system work ?

### ISSUE THREAD

**Issue by 59e5aaf4** [CrowdStrike/Falcon-Toolkit#46]
Hello.

I've been trying to pass the https://github.com/bk-cs/rtr scripts some JSON parameters trying all sorts of quoting combination, only ending up with one of these :
* `Unexpected token`
* `Script parsing exception at line:115 character:11` (script fails to decode json)
* `Error: unrecognized arguments:` (falcon-toolkit syas my command is wrong)

I also tried briefly using the "rtr()" function from the py shell but it just points back to the same command interpreter right ?

Sample command :
* `runscript -CloudFile get_fileinfo.ps1 -CommandLine '{"File":"a.txt"}'`

Q: What is the proper way to pass arguments to these powershell script that expect a json, from the rtr live shell ?

Thanks !

**Comment by ChristopherHammond13** [comment]
Hey! You should use double quotes within the toolkit, and it will convert them to triple backticks when the API call is issued on the backend.

If you want to run a script from your local system, the easiest way is to use `runscript -WorkstationPath /path/to/script.ps1`, and you won't need to worry about escaping anything.
