### ISSUE TITLE
RTR shell - mount is missing from the windows shell

### ISSUE THREAD

**Issue by 59e5aaf4** [CrowdStrike/Falcon-Toolkit#96]
Somehow falcon-toolkit doesn't know about "mount" on windows:

```
C:\> mount
mount is not a recognized command, alias, or macro
```
While it exists :D

API IN : `mount`
API OUT:
```
Name Used (GB) Free (GB) Root
---- --------- --------- ----
C    358,915   116,292   C:\ 
D    586,39    1275,896  D:\ 
```
cheers

**Comment by ChristopherHammond13** [comment]
Nice catch! We have support for the read only `mount` command in Caracara too, so this is a fairly trivial fix. Thanks for raising!
