### ISSUE TITLE
Can't use runscript against Cloud resources

### ISSUE THREAD

**Issue by rsshilli** [CrowdStrike/Falcon-Toolkit#97]
Hello,

I'm relatively new to CrowdStrike. This tool looks amazing except that I can't get it to actually run a script for me.

My steps to reproduce:

1. Go to Host setup and management -> Response scripts and files
1.  Click "+ Create Script" to add a custom script.
1. Call it "test.sh" and add the following "Script content":
    ```
    #!/usr/bin/env zsh
    
    echo Hello world
    ```
1. Save it
1. Go to the command line and connect to a machine using the Falcon Toolkit
    ```
    falcon shell -d <some device id>
    ```
1.  Try to run your new script
    ```
    falcon shell -d <some device id>
    ```
**Expected result**: The script runs and returns "Hello World"
**Actual result**: 
```
/ # runscript -CloudFile=test.sh
Executing command: runscript -CloudFile="test.sh" -Timeout=30
aws-dev-open-vpn-server:
aws-dev-open-vpn-server:
At least one error was detected. Check the log file for full details.
List of errors detected:
-> The file test.sh could not be found
/ #
```

**Comment by rsshilli** [comment]
Well, I figured the answer out myself. The `test.sh` file must give access to "RTR Administrator and RTR Active Responder" and not just "RTR Administrator".

BTW - this isn't a limitation when I'm connecting to RTR using the browser.  Also, it would be nice to have a hint to check the permissions.

**Comment by ChristopherHammond13** [comment]
Ah, yes. The permission model here is important to understand for everything to work. Unfortunately the API does not provide for a way to for a token to inspect its own permissions in the public API gateway, so it is not possible for the Toolkit to tell you what access level it has without attempting a series of differently privileged API calls and reporting whether they 403'd or not.

If anybody has a better way to implement this check I would be open to exploring it, but it's not a (neatly) solvable problem right now.
