### ISSUE TITLE
Add the ability to get device maintenance token

### ISSUE THREAD

**Issue by BaDxKaRMa** [CrowdStrike/Falcon-Toolkit#99]
Leveraging host_search to get device maintenance token(s) would be great.

**Comment by ChristopherHammond13** [comment]
This is a great suggestion! Thank you for raising.

**Comment by ChristopherHammond13** [comment]
Once the backend functionality for this has been merged into Caracara, this is the next feature on our backlog.

**Comment by BaDxKaRMa** [comment]
Thanks! That should fully replace the less awesome version of this toolkit that I made. lol

**Comment by ChristopherHammond13** [comment]
Glad to hear that this might help!
